### ISSUE TITLE
[PE-D][Tester E] Documentation Bug: Incorrect formatting of the JUNIT portion

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-1/tp#248]
![image.png](https://raw.githubusercontent.com/woke02/ped/main/files/5d57a964-2897-4b80-afce-8b225ac42f28.png)
"Junit - Testing framework" part in user guide is incorrectly formatted

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: woke02/ped#9

**Comment by yikyak02** [comment]
this happens during conversion from markdown to pdf, we will try to solve it
