### ISSUE TITLE
[PE-D][Tester D] Cannot add contact for different person with same phone number.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-1/tp#250]
![Screenshot 2024-11-08 153607.png](https://raw.githubusercontent.com/tayxuenye/ped/main/files/8fbd6533-b322-45ac-b9b8-c2a4c1be3e6b.png)

I understand the phone number needs to be different than any other users in the address book but what if both users are related and use the same phone? Maybe if you wish to force different phone numbers you could be clearer to the user that the contact cannot be added because it uses the same phone number instead of letting the user guess why.

The input I used is shown in the screenshot.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: tayxuenye/ped#5

**Comment by yikyak02** [comment]
phone number has to to be unique to each person, will update in UG and DG.
