### ISSUE TITLE
[PE-D][Tester E] Bug: markCustomerOrder Command Changes the order of customer orders

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-1/tp#272]
This is the initial customer orders:

![image.png](https://raw.githubusercontent.com/woke02/ped/main/files/288ab84e-34c6-4930-8f26-7e78137778c3.png)

After running "markCustomerOrder 1":
![image.png](https://raw.githubusercontent.com/woke02/ped/main/files/a609ebfd-8d4c-4a2b-9e41-fb3408648a64.png)

When using the markCustomerOrder 1 command, the application states that "Customer order 1 is marked as completed," but in reality, a different order (e.g., Customer Order 2) is marked as completed. This issue arises due to a change in the order of the customer order list, leading to confusion and incorrect status updates.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: woke02/ped#20

**Comment by yikyak02** [comment]
intended
