### ISSUE TITLE
[PE-D][Tester B] Command words are case sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-1/tp#289]
![image.png](https://raw.githubusercontent.com/TY1Fan/ped/main/files/644701f9-aa3a-4bb1-b945-a91fe6d87114.png)

### Steps to reproduce:
1. Enter this line:
```
AddContact n/Tim p/81234567 e/emily@example.com a/456 Cupcake Road, Block 123, 0
```

### Expected:
I was expecting the command word to be case-insensitive as the command AddContact is reasonable and should execute the addContact command

### Actual:
The app throws an unknown command error.

### Suggestions:
Let's change the command words to be case-insensitive so that the app will be more intuitive to users.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: TY1Fan/ped#6

**Comment by yikyak02** [comment]
specified in ug that command words are case sensitive
