### ISSUE TITLE
[PE-D][Tester B] Inconsistent Error message for markCustomerOrder

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-1/tp#331]
![image.png](https://raw.githubusercontent.com/TY1Fan/ped/main/files/0557c6d4-42d4-4fce-944c-efda44d10e4d.png)

![image.png](https://raw.githubusercontent.com/TY1Fan/ped/main/files/7761ef21-7794-4638-a9f1-45f956e69e51.png)

### Steps to reproduce:
1. Enter this line:
```
markCustomerOrder -1
```
1. Observe the error message for this input
1. Then key in this line:
```
markCustomerOrder a
```
1. Observe that both invalid index have different error message

### Expected:
I think the error message for this 2 test cases should be the same. Or should differ by telling the user whether the error is caused by negative index or non-numerical index

### Actual:
The error provided have different formats and both did not mention why that index is invalid.

### Suggestions:
Let's standardize the error message format and add more description on the error thrown.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: TY1Fan/ped#15

**Comment by yikyak02** [comment]
done
